version: "3.9"

services:
  proxy:
    image: nginx:stable
    restart: always
    ports:
      - 8889:80
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    container_name: db
    image: postgres:latest
    build:
      context: ./db
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
    ports:
      - "5444:5432"

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
#    environment:
#      - DATABASE_URL=
#      - SECRET_KEY=
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - net
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  frontend:
    container_name: frontend
    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - net

networks:
  net:
    driver: bridge
