version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./dd/backup:/backup
    ports:
      - "5444:5432"

  backend:
    container_name: back
    build: ./backend
    ports:
      - 8000:8000
#    environment:
#      - DATABASE_URL=
#      - SECRET_KEY=
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    container_name: front
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - 3000:3000